# Group prices by tariff_type.retailer.fy_ending
# All prices are exclusive of GST

# Supply charge is in c/day
# Usage is is c/kWh
# Demand is in $/kW/mth

[t11.ergon.2017]
supply_charge = 89.572
usage = 24.61

[t11.ergon.2018]
supply_charge = 87.133
usage = 25.89

[t11.ergon.2019]
supply_charge = 88.948
usage = 25.298

[t11.ergon.2020]
supply_charge = 90.345
usage = 23.661

[t11.agl.2017]
supply_charge = 98.51
usage = 24.61

[t11.agl.2018]
supply_charge = 100
usage = 26

[t11.agl.2019]
supply_charge = 99
usage = 25.5

[t11.origin.2017]
supply_charge = 116.47
usage = 23.26

[t11.origin.2018]
supply_charge = 114.19
usage = 24.51

[t11.origin.2019]
supply_charge = 112.73
usage = 24.2

[t12.ergon.2017]
supply_charge = 101.306
peak_usage = 55.865
shoulder_usage = 19.859
offpeak_usage = 19.859
tou_def = 'qld-regional'

[t12.ergon.2018]
supply_charge = 89.848
peak_usage = 61.137
shoulder_usage = 21.07
offpeak_usage = 21.07
tou_def = 'qld-regional'

[t12.ergon.2019]
supply_charge = 77.628
peak_usage = 62.666
shoulder_usage = 21.474
offpeak_usage = 21.474
tou_def = 'qld-regional'

[t12.ergon.2020]
supply_charge = 78.226
peak_usage = 62.265
shoulder_usage = 19.872
offpeak_usage = 19.872
tou_def = 'qld-regional'

[t12.agl.2017]
supply_charge = 95.69
peak_usage = 29.79
shoulder_usage = 21.47
offpeak_usage = 17.49
tou_def = 'qld-south-east'

[t12.agl.2018]
supply_charge = 101
peak_usage = 35
shoulder_usage = 26
offpeak_usage = 22
tou_def = 'qld-south-east'

[t12.agl.2019]
supply_charge = 99
peak_usage = 34.5
shoulder_usage = 25.5
offpeak_usage = 21.5
tou_def = 'qld-south-east'

[t12.origin.2017]
supply_charge = 116.47
peak_usage = 30.73
shoulder_usage = 22.15
offpeak_usage = 17.97
tou_def = 'qld-south-east'

[t12.origin.2018]
supply_charge = 114.19
peak_usage = 32.38
shoulder_usage = 23.24
offpeak_usage = 18.94
tou_def = 'qld-south-east'

[t12.origin.2019]
supply_charge = 112.73
peak_usage = 31.97
shoulder_usage = 23.04
offpeak_usage = 18.7
tou_def = 'qld-south-east'

[t14.ergon.2017]
supply_charge = 60.514
usage = 14.984
demand_peak = 61.79
demand_shoulder = 11.258
demand_shoulder_min = 3.0
tou_def = 'qld-regional'

[t14.ergon.2018]
supply_charge = 45.749
usage = 17.43
demand_peak = 65.818
demand_shoulder = 9.931
demand_shoulder_min = 3.0
tou_def = 'qld-regional'

[t14.ergon.2019]
supply_charge = 46.42
usage = 17.593
demand_peak = 62.777
demand_shoulder = 9.241
demand_shoulder_min = 3.0
tou_def = 'qld-regional'

[t14.ergon.2020]
supply_charge = 45.773
usage = 15.835
demand_peak = 59.412
demand_shoulder = 8.532
demand_shoulder_min = 3.0
tou_def = 'qld-regional'
