# Group prices by tariff_type.retailer.fy_starting
# All prices are exclusive of GST

# Supply charge is in c/day
# Usage is is c/kWh
# Demand is in $/kW/mth

[t11.ergon.2016]
supply_charge = 89.572
usage = 24.61

[t11.ergon.2017]
supply_charge = 87.133
usage = 25.89

[t11.ergon.2018]
supply_charge = 88.948
usage = 25.298

[t11.agl.2016]
supply_charge = 98.51
usage = 24.61

[t11.agl.2017]
supply_charge = 100
usage = 26

[t11.agl.2018]
supply_charge = 99
usage = 25.5

[t11.origin.2016]
supply_charge = 116.47
usage = 23.26

[t11.origin.2017]
supply_charge = 114.19
usage = 24.51

[t11.origin.2018]
supply_charge = 112.73
usage = 24.2

[t12.ergon.2016]
supply_charge = 101.306
peak_usage = 55.865
shoulder_usage = 19.859
offpeak_usage = 19.859
periods = 'ergon-periods'

[t12.ergon.2017]
supply_charge = 89.848
peak_usage = 61.137
shoulder_usage = 21.07
offpeak_usage = 21.07
periods = 'ergon-periods'

[t12.ergon.2018]
supply_charge = 77.628
peak_usage = 62.666
shoulder_usage = 21.474
offpeak_usage = 21.474
periods = 'ergon-periods'

[t12.agl.2016]
supply_charge = 95.69
peak_usage = 29.79
shoulder_usage = 21.47
offpeak_usage = 17.49
periods = 'seq-periods'

[t12.agl.2017]
supply_charge = 101
peak_usage = 35
shoulder_usage = 26
offpeak_usage = 22
periods = 'seq-periods'

[t12.agl.2018]
supply_charge = 99
peak_usage = 34.5
shoulder_usage = 25.5
offpeak_usage = 21.5
periods = 'seq-periods'

[t12.origin.2016]
supply_charge = 116.47
peak_usage = 30.73
shoulder_usage = 22.15
offpeak_usage = 17.97
periods = 'seq-periods'

[t12.origin.2017]
supply_charge = 114.19
peak_usage = 32.38
shoulder_usage = 23.24
offpeak_usage = 18.94
periods = 'seq-periods'

[t12.origin.2018]
supply_charge = 112.73
peak_usage = 31.97
shoulder_usage = 23.04
offpeak_usage = 18.7
periods = 'seq-periods'

[t14.ergon.2016]
supply_charge = 60.514
usage = 14.984
demand_peak = 61.79
demand_shoulder = 11.258
demand_shoulder_min = 3.0
periods = 'ergon-periods'

[t14.ergon.2017]
supply_charge = 45.749
usage = 17.43
demand_peak = 65.818
demand_shoulder = 9.931
demand_shoulder_min = 3.0
periods = 'ergon-periods'

[t14.ergon.2018]
supply_charge = 46.42
usage = 17.593
demand_peak = 62.777
demand_shoulder = 9.241
demand_shoulder_min = 3.0
periods = 'ergon-periods'

# Peak and shoulder periods are different
# Specify each unique combination with a new name

[seq-periods]
peak_months = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
peak_days = [1, 2, 3, 4, 5]
peak_start = "16:00"
peak_end = "20:00"
shoulder_months = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
shoulder_days = [0, 1, 2, 3, 4, 5, 6]
shoulder_start = "07:00"
shoulder_end = "22:00"

[ergon-periods]
peak_months = [1, 2, 12]
peak_days = [0, 1, 2, 3, 4, 5, 6]
peak_start = "15:00"
peak_end = "21:30"
shoulder_months = [3, 4, 5, 6, 7, 8, 9, 10, 11]
shoulder_days = [0, 1, 2, 3, 4, 5, 6]
shoulder_start = "15:00"
shoulder_end = "21:30"
