# Peak times are the primary definition
# Shoulder times include all times specified that are not peak
# Offpeak times include any time not convered by peak or shoulder

[qld-south-east]
peak_months = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
peak_days = [1, 2, 3, 4, 5]
peak_start = "16:00"
peak_end = "20:00"
shoulder_months = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
shoulder_days = [0, 1, 2, 3, 4, 5, 6]
shoulder_start = "07:00"
shoulder_end = "22:00"

[qld-regional]
peak_months = [1, 2, 12]
peak_days = [0, 1, 2, 3, 4, 5, 6]
peak_start = "15:00"
peak_end = "21:30"
shoulder_months = [3, 4, 5, 6, 7, 8, 9, 10, 11]
shoulder_days = [0, 1, 2, 3, 4, 5, 6]
shoulder_start = "15:00"
shoulder_end = "21:30"
